// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CustomerColumns holds the columns for the "customer" table.
	CustomerColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "customer_name", Type: field.TypeString},
		{Name: "account_number", Type: field.TypeString, Unique: true},
		{Name: "id_currency", Type: field.TypeInt, Default: 550},
		{Name: "id_country", Type: field.TypeInt, Default: 40},
		{Name: "alias", Type: field.TypeString, Unique: true},
		{Name: "ab_key", Type: field.TypeString, Unique: true},
		{Name: "state", Type: field.TypeString, Nullable: true},
		{Name: "tmc_client_number", Type: field.TypeString, Unique: true},
		{Name: "tag", Type: field.TypeEnum, Enums: []string{"1", "2", "3"}, Default: "3"},
	}
	// CustomerTable holds the schema information for the "customer" table.
	CustomerTable = &schema.Table{
		Name:       "customer",
		Columns:    CustomerColumns,
		PrimaryKey: []*schema.Column{CustomerColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CustomerTable,
	}
)

func init() {
	CustomerTable.Annotation = &entsql.Annotation{
		Table: "customer",
	}
}
