// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/naelcodes/ab-backend/internal/ent/customer"
)

// CustomerCreate is the builder for creating a Customer entity.
type CustomerCreate struct {
	config
	mutation *CustomerMutation
	hooks    []Hook
}

// SetCustomerName sets the "customer_name" field.
func (cc *CustomerCreate) SetCustomerName(s string) *CustomerCreate {
	cc.mutation.SetCustomerName(s)
	return cc
}

// SetAccountNumber sets the "account_number" field.
func (cc *CustomerCreate) SetAccountNumber(s string) *CustomerCreate {
	cc.mutation.SetAccountNumber(s)
	return cc
}

// SetIDCurrency sets the "id_currency" field.
func (cc *CustomerCreate) SetIDCurrency(i int) *CustomerCreate {
	cc.mutation.SetIDCurrency(i)
	return cc
}

// SetNillableIDCurrency sets the "id_currency" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableIDCurrency(i *int) *CustomerCreate {
	if i != nil {
		cc.SetIDCurrency(*i)
	}
	return cc
}

// SetIDCountry sets the "id_country" field.
func (cc *CustomerCreate) SetIDCountry(i int) *CustomerCreate {
	cc.mutation.SetIDCountry(i)
	return cc
}

// SetNillableIDCountry sets the "id_country" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableIDCountry(i *int) *CustomerCreate {
	if i != nil {
		cc.SetIDCountry(*i)
	}
	return cc
}

// SetAlias sets the "alias" field.
func (cc *CustomerCreate) SetAlias(s string) *CustomerCreate {
	cc.mutation.SetAlias(s)
	return cc
}

// SetAbKey sets the "ab_key" field.
func (cc *CustomerCreate) SetAbKey(s string) *CustomerCreate {
	cc.mutation.SetAbKey(s)
	return cc
}

// SetState sets the "state" field.
func (cc *CustomerCreate) SetState(s string) *CustomerCreate {
	cc.mutation.SetState(s)
	return cc
}

// SetNillableState sets the "state" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableState(s *string) *CustomerCreate {
	if s != nil {
		cc.SetState(*s)
	}
	return cc
}

// SetTmcClientNumber sets the "tmc_client_number" field.
func (cc *CustomerCreate) SetTmcClientNumber(s string) *CustomerCreate {
	cc.mutation.SetTmcClientNumber(s)
	return cc
}

// SetTag sets the "Tag" field.
func (cc *CustomerCreate) SetTag(c customer.Tag) *CustomerCreate {
	cc.mutation.SetTag(c)
	return cc
}

// SetNillableTag sets the "Tag" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableTag(c *customer.Tag) *CustomerCreate {
	if c != nil {
		cc.SetTag(*c)
	}
	return cc
}

// Mutation returns the CustomerMutation object of the builder.
func (cc *CustomerCreate) Mutation() *CustomerMutation {
	return cc.mutation
}

// Save creates the Customer in the database.
func (cc *CustomerCreate) Save(ctx context.Context) (*Customer, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CustomerCreate) SaveX(ctx context.Context) *Customer {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CustomerCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CustomerCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CustomerCreate) defaults() {
	if _, ok := cc.mutation.IDCurrency(); !ok {
		v := customer.DefaultIDCurrency
		cc.mutation.SetIDCurrency(v)
	}
	if _, ok := cc.mutation.IDCountry(); !ok {
		v := customer.DefaultIDCountry
		cc.mutation.SetIDCountry(v)
	}
	if _, ok := cc.mutation.Tag(); !ok {
		v := customer.DefaultTag
		cc.mutation.SetTag(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CustomerCreate) check() error {
	if _, ok := cc.mutation.CustomerName(); !ok {
		return &ValidationError{Name: "customer_name", err: errors.New(`ent: missing required field "Customer.customer_name"`)}
	}
	if _, ok := cc.mutation.AccountNumber(); !ok {
		return &ValidationError{Name: "account_number", err: errors.New(`ent: missing required field "Customer.account_number"`)}
	}
	if _, ok := cc.mutation.IDCurrency(); !ok {
		return &ValidationError{Name: "id_currency", err: errors.New(`ent: missing required field "Customer.id_currency"`)}
	}
	if _, ok := cc.mutation.IDCountry(); !ok {
		return &ValidationError{Name: "id_country", err: errors.New(`ent: missing required field "Customer.id_country"`)}
	}
	if _, ok := cc.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "Customer.alias"`)}
	}
	if _, ok := cc.mutation.AbKey(); !ok {
		return &ValidationError{Name: "ab_key", err: errors.New(`ent: missing required field "Customer.ab_key"`)}
	}
	if _, ok := cc.mutation.TmcClientNumber(); !ok {
		return &ValidationError{Name: "tmc_client_number", err: errors.New(`ent: missing required field "Customer.tmc_client_number"`)}
	}
	if _, ok := cc.mutation.Tag(); !ok {
		return &ValidationError{Name: "Tag", err: errors.New(`ent: missing required field "Customer.Tag"`)}
	}
	if v, ok := cc.mutation.Tag(); ok {
		if err := customer.TagValidator(v); err != nil {
			return &ValidationError{Name: "Tag", err: fmt.Errorf(`ent: validator failed for field "Customer.Tag": %w`, err)}
		}
	}
	return nil
}

func (cc *CustomerCreate) sqlSave(ctx context.Context) (*Customer, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CustomerCreate) createSpec() (*Customer, *sqlgraph.CreateSpec) {
	var (
		_node = &Customer{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(customer.Table, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.CustomerName(); ok {
		_spec.SetField(customer.FieldCustomerName, field.TypeString, value)
		_node.CustomerName = value
	}
	if value, ok := cc.mutation.AccountNumber(); ok {
		_spec.SetField(customer.FieldAccountNumber, field.TypeString, value)
		_node.AccountNumber = value
	}
	if value, ok := cc.mutation.IDCurrency(); ok {
		_spec.SetField(customer.FieldIDCurrency, field.TypeInt, value)
		_node.IDCurrency = value
	}
	if value, ok := cc.mutation.IDCountry(); ok {
		_spec.SetField(customer.FieldIDCountry, field.TypeInt, value)
		_node.IDCountry = value
	}
	if value, ok := cc.mutation.Alias(); ok {
		_spec.SetField(customer.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := cc.mutation.AbKey(); ok {
		_spec.SetField(customer.FieldAbKey, field.TypeString, value)
		_node.AbKey = value
	}
	if value, ok := cc.mutation.State(); ok {
		_spec.SetField(customer.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := cc.mutation.TmcClientNumber(); ok {
		_spec.SetField(customer.FieldTmcClientNumber, field.TypeString, value)
		_node.TmcClientNumber = value
	}
	if value, ok := cc.mutation.Tag(); ok {
		_spec.SetField(customer.FieldTag, field.TypeEnum, value)
		_node.Tag = value
	}
	return _node, _spec
}

// CustomerCreateBulk is the builder for creating many Customer entities in bulk.
type CustomerCreateBulk struct {
	config
	err      error
	builders []*CustomerCreate
}

// Save creates the Customer entities in the database.
func (ccb *CustomerCreateBulk) Save(ctx context.Context) ([]*Customer, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Customer, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CustomerCreateBulk) SaveX(ctx context.Context) []*Customer {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CustomerCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CustomerCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
