// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/naelcodes/ab-backend/ent/invoice"
	"github.com/naelcodes/ab-backend/ent/predicate"
	"github.com/naelcodes/ab-backend/ent/travelitem"
)

// TravelItemQuery is the builder for querying TravelItem entities.
type TravelItemQuery struct {
	config
	ctx         *QueryContext
	order       []travelitem.OrderOption
	inters      []Interceptor
	predicates  []predicate.TravelItem
	withInvoice *InvoiceQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TravelItemQuery builder.
func (tiq *TravelItemQuery) Where(ps ...predicate.TravelItem) *TravelItemQuery {
	tiq.predicates = append(tiq.predicates, ps...)
	return tiq
}

// Limit the number of records to be returned by this query.
func (tiq *TravelItemQuery) Limit(limit int) *TravelItemQuery {
	tiq.ctx.Limit = &limit
	return tiq
}

// Offset to start from.
func (tiq *TravelItemQuery) Offset(offset int) *TravelItemQuery {
	tiq.ctx.Offset = &offset
	return tiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tiq *TravelItemQuery) Unique(unique bool) *TravelItemQuery {
	tiq.ctx.Unique = &unique
	return tiq
}

// Order specifies how the records should be ordered.
func (tiq *TravelItemQuery) Order(o ...travelitem.OrderOption) *TravelItemQuery {
	tiq.order = append(tiq.order, o...)
	return tiq
}

// QueryInvoice chains the current query on the "invoice" edge.
func (tiq *TravelItemQuery) QueryInvoice() *InvoiceQuery {
	query := (&InvoiceClient{config: tiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(travelitem.Table, travelitem.FieldID, selector),
			sqlgraph.To(invoice.Table, invoice.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, travelitem.InvoiceTable, travelitem.InvoiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(tiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TravelItem entity from the query.
// Returns a *NotFoundError when no TravelItem was found.
func (tiq *TravelItemQuery) First(ctx context.Context) (*TravelItem, error) {
	nodes, err := tiq.Limit(1).All(setContextOp(ctx, tiq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{travelitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tiq *TravelItemQuery) FirstX(ctx context.Context) *TravelItem {
	node, err := tiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TravelItem ID from the query.
// Returns a *NotFoundError when no TravelItem ID was found.
func (tiq *TravelItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tiq.Limit(1).IDs(setContextOp(ctx, tiq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{travelitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tiq *TravelItemQuery) FirstIDX(ctx context.Context) int {
	id, err := tiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TravelItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TravelItem entity is found.
// Returns a *NotFoundError when no TravelItem entities are found.
func (tiq *TravelItemQuery) Only(ctx context.Context) (*TravelItem, error) {
	nodes, err := tiq.Limit(2).All(setContextOp(ctx, tiq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{travelitem.Label}
	default:
		return nil, &NotSingularError{travelitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tiq *TravelItemQuery) OnlyX(ctx context.Context) *TravelItem {
	node, err := tiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TravelItem ID in the query.
// Returns a *NotSingularError when more than one TravelItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (tiq *TravelItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tiq.Limit(2).IDs(setContextOp(ctx, tiq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{travelitem.Label}
	default:
		err = &NotSingularError{travelitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tiq *TravelItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := tiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TravelItems.
func (tiq *TravelItemQuery) All(ctx context.Context) ([]*TravelItem, error) {
	ctx = setContextOp(ctx, tiq.ctx, "All")
	if err := tiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TravelItem, *TravelItemQuery]()
	return withInterceptors[[]*TravelItem](ctx, tiq, qr, tiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tiq *TravelItemQuery) AllX(ctx context.Context) []*TravelItem {
	nodes, err := tiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TravelItem IDs.
func (tiq *TravelItemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tiq.ctx.Unique == nil && tiq.path != nil {
		tiq.Unique(true)
	}
	ctx = setContextOp(ctx, tiq.ctx, "IDs")
	if err = tiq.Select(travelitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tiq *TravelItemQuery) IDsX(ctx context.Context) []int {
	ids, err := tiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tiq *TravelItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tiq.ctx, "Count")
	if err := tiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tiq, querierCount[*TravelItemQuery](), tiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tiq *TravelItemQuery) CountX(ctx context.Context) int {
	count, err := tiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tiq *TravelItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tiq.ctx, "Exist")
	switch _, err := tiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tiq *TravelItemQuery) ExistX(ctx context.Context) bool {
	exist, err := tiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TravelItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tiq *TravelItemQuery) Clone() *TravelItemQuery {
	if tiq == nil {
		return nil
	}
	return &TravelItemQuery{
		config:      tiq.config,
		ctx:         tiq.ctx.Clone(),
		order:       append([]travelitem.OrderOption{}, tiq.order...),
		inters:      append([]Interceptor{}, tiq.inters...),
		predicates:  append([]predicate.TravelItem{}, tiq.predicates...),
		withInvoice: tiq.withInvoice.Clone(),
		// clone intermediate query.
		sql:  tiq.sql.Clone(),
		path: tiq.path,
	}
}

// WithInvoice tells the query-builder to eager-load the nodes that are connected to
// the "invoice" edge. The optional arguments are used to configure the query builder of the edge.
func (tiq *TravelItemQuery) WithInvoice(opts ...func(*InvoiceQuery)) *TravelItemQuery {
	query := (&InvoiceClient{config: tiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tiq.withInvoice = query
	return tiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TotalPrice float64 `json:"total_price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TravelItem.Query().
//		GroupBy(travelitem.FieldTotalPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tiq *TravelItemQuery) GroupBy(field string, fields ...string) *TravelItemGroupBy {
	tiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TravelItemGroupBy{build: tiq}
	grbuild.flds = &tiq.ctx.Fields
	grbuild.label = travelitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TotalPrice float64 `json:"total_price,omitempty"`
//	}
//
//	client.TravelItem.Query().
//		Select(travelitem.FieldTotalPrice).
//		Scan(ctx, &v)
func (tiq *TravelItemQuery) Select(fields ...string) *TravelItemSelect {
	tiq.ctx.Fields = append(tiq.ctx.Fields, fields...)
	sbuild := &TravelItemSelect{TravelItemQuery: tiq}
	sbuild.label = travelitem.Label
	sbuild.flds, sbuild.scan = &tiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TravelItemSelect configured with the given aggregations.
func (tiq *TravelItemQuery) Aggregate(fns ...AggregateFunc) *TravelItemSelect {
	return tiq.Select().Aggregate(fns...)
}

func (tiq *TravelItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tiq); err != nil {
				return err
			}
		}
	}
	for _, f := range tiq.ctx.Fields {
		if !travelitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tiq.path != nil {
		prev, err := tiq.path(ctx)
		if err != nil {
			return err
		}
		tiq.sql = prev
	}
	return nil
}

func (tiq *TravelItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TravelItem, error) {
	var (
		nodes       = []*TravelItem{}
		withFKs     = tiq.withFKs
		_spec       = tiq.querySpec()
		loadedTypes = [1]bool{
			tiq.withInvoice != nil,
		}
	)
	if tiq.withInvoice != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, travelitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TravelItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TravelItem{config: tiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tiq.withInvoice; query != nil {
		if err := tiq.loadInvoice(ctx, query, nodes, nil,
			func(n *TravelItem, e *Invoice) { n.Edges.Invoice = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tiq *TravelItemQuery) loadInvoice(ctx context.Context, query *InvoiceQuery, nodes []*TravelItem, init func(*TravelItem), assign func(*TravelItem, *Invoice)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TravelItem)
	for i := range nodes {
		if nodes[i].id_invoice == nil {
			continue
		}
		fk := *nodes[i].id_invoice
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(invoice.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "id_invoice" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tiq *TravelItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tiq.querySpec()
	_spec.Node.Columns = tiq.ctx.Fields
	if len(tiq.ctx.Fields) > 0 {
		_spec.Unique = tiq.ctx.Unique != nil && *tiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tiq.driver, _spec)
}

func (tiq *TravelItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(travelitem.Table, travelitem.Columns, sqlgraph.NewFieldSpec(travelitem.FieldID, field.TypeInt))
	_spec.From = tiq.sql
	if unique := tiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tiq.path != nil {
		_spec.Unique = true
	}
	if fields := tiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, travelitem.FieldID)
		for i := range fields {
			if fields[i] != travelitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tiq *TravelItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tiq.driver.Dialect())
	t1 := builder.Table(travelitem.Table)
	columns := tiq.ctx.Fields
	if len(columns) == 0 {
		columns = travelitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tiq.sql != nil {
		selector = tiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tiq.ctx.Unique != nil && *tiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tiq.predicates {
		p(selector)
	}
	for _, p := range tiq.order {
		p(selector)
	}
	if offset := tiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TravelItemGroupBy is the group-by builder for TravelItem entities.
type TravelItemGroupBy struct {
	selector
	build *TravelItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tigb *TravelItemGroupBy) Aggregate(fns ...AggregateFunc) *TravelItemGroupBy {
	tigb.fns = append(tigb.fns, fns...)
	return tigb
}

// Scan applies the selector query and scans the result into the given value.
func (tigb *TravelItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tigb.build.ctx, "GroupBy")
	if err := tigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TravelItemQuery, *TravelItemGroupBy](ctx, tigb.build, tigb, tigb.build.inters, v)
}

func (tigb *TravelItemGroupBy) sqlScan(ctx context.Context, root *TravelItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tigb.fns))
	for _, fn := range tigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tigb.flds)+len(tigb.fns))
		for _, f := range *tigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TravelItemSelect is the builder for selecting fields of TravelItem entities.
type TravelItemSelect struct {
	*TravelItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tis *TravelItemSelect) Aggregate(fns ...AggregateFunc) *TravelItemSelect {
	tis.fns = append(tis.fns, fns...)
	return tis
}

// Scan applies the selector query and scans the result into the given value.
func (tis *TravelItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tis.ctx, "Select")
	if err := tis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TravelItemQuery, *TravelItemSelect](ctx, tis.TravelItemQuery, tis, tis.inters, v)
}

func (tis *TravelItemSelect) sqlScan(ctx context.Context, root *TravelItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tis.fns))
	for _, fn := range tis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
